// Generated by CoffeeScript 1.9.3
(function() {
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  window.ChipCount = (function(superClass) {
    extend(ChipCount, superClass);

    function ChipCount() {
      return ChipCount.__super__.constructor.apply(this, arguments);
    }

    ChipCount.prototype.initialize = function(params) {
      return this.set({
        chips: 5000
      });
    };

    return ChipCount;

  })(Backbone.Model);

}).call(this);

//# sourceMappingURL=ChipCount.js.map
