// Generated by CoffeeScript 1.9.3
(function() {
  window.bet = new Bet();

  window.betView = new BetView({
    model: bet
  }).$el.appendTo('body');

  new AppView({
    model: new App()
  }).$el.appendTo('body');

}).call(this);

//# sourceMappingURL=main.js.map
